### PR TITLE
Set new rootfs partitions sizes

### PR DESCRIPTION
**Pull request by floion**
fixes https://github.com/resin-os/resinos/issues/168

### CODE REVIEW

**Comment by agherzan** [comment]
This looks good but please merge it along with the meta-resin update which implements that rootfs size.

**Comment by floion** [comment]
Will add the meta-resin update to this PR as soon as https://github.com/resin-os/meta-resin/pull/577 is merged

**Comment by floion** [comment]
Even though this PR is independent of the meta-resin Pr and fixes the issue just by itself

**Comment by floion** [comment]
I would actually not have to wait for the other Pr to get merged before.

**Comment by agherzan** [comment]
I think this should go hand in hand with a meta-resin release which brings the rootfs size as stated above. This would clarify the situation in the future even though I do agree that the current state is already broken.

**Comment by floion** [comment]
Any functional reason to wait for that PR? This PR by itself does not need the meta-resin PR in order to fix the flashing problem that this PR is supposed to address

**Comment by agherzan** [comment]
But is this PR actually fixing the problem? It will not until the meta-resin submodule will be in, right? So having them together will bring a known working state and actually fix the problem.

**Comment by floion** [comment]
Yes, this PR fixes the problem as I said already above

**Comment by agherzan** [comment]
Uh! Just because we go bigger and not smaller. I got it now. It was not clear how was it fixed.

**Pull request merged**
