### PR TITLE
Update to use the simplified JSON building process on resin-edison

### PR DESCRIPTION
**Pull request by emirotin**
This implements resin-os/resin-yocto-scripts#31

Signed-off-by: Eugene Mirotin eugene@resin.io

@agherzan @floion

### CODE REVIEW

**Comment by emirotin** [comment]
This repo doesn't seem to have the build status connected?

**Comment by Page-** [comment]
SGTM

**Comment by Page-** [comment]
It works by polling @emirotin so it was probably just waiting on that before it appeared

**Comment by floion** [comment]
LGTM

**Pull request merged**
