### PR TITLE
Edison aufs fix master

### PR DESCRIPTION
**Pull request by agherzan**
Fixes: https://github.com/resin-os/resinos/issues/185

### CODE REVIEW

**Comment by floion** [comment]
Shall we do the same to the 1.X branch?

**Comment by agherzan** [comment]
@floion 1.X is not on aufs so I'd say to not backport this.

**Comment by floion** [comment]
But we will have different kernel versions between 1.X and master. If you are okay with that then it's good

**Comment by agherzan** [comment]
You have a point here. Let's not call for trouble and backport it. Will do it.

**Pull request merged**
