### PR TITLE
Introduce versioning for coffee

### PR DESCRIPTION
**Pull request by floion**
@agherzan @michal-mazurek

### CODE REVIEW

**Comment by agherzan** [comment]
LGTM

**Comment by Page-** [comment]
What is this for @floion ?

**Comment by floion** [comment]
It's for resin-cli (for example) to be able to know when changes are done on the device-type.json as a consequence of some changes in the image itself. To be able to have a mapping between device-type.json and the device image @page

**Comment by Page-** [comment]
I don't believe this will help with that particular issue, but having a version for the device-type schema is ok I guess, can you make it `version: 1` though, so that it's easy to do numeric comparison

**Comment by floion** [comment]
Yeah, it will be easier for future architectural changes so we might as well introduce it now and bump it each time there is an impacting change so that other components can be easily made aware of such changes. And about the number property you are correct, we already made it a number property in the resin-artik and resin-intel repositories and merged it, I need to redo the rest of the PRs with the same change. Thanks for the input, Page

**Pull request merged**
